# FROM python:3.10-slim

# WORKDIR /app

# ENV PYTHONDONTWRITEBYTECODE=1
# ENV PYTHONUNBUFFERED=1
# ENV PYTHONPATH=/app/src

# COPY job_matcher_app/skill_worker/requirements.skill_worker.txt /app/requirements.skill_worker.txt

# RUN apt-get update \
#     && apt-get install -y --no-install-recommends gcc g++ \
#     && pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cpu torch \
#     && pip install --no-cache-dir -r /app/requirements.skill_worker.txt \
#     && apt-get purge -y --auto-remove gcc g++ \
#     && rm -rf /var/lib/apt/lists/*

# COPY job_matcher_app/skill_worker.py /app/src/job_matcher_app/skill_worker.py

# CMD ["python", "-m", "job_matcher_app.skill_worker"]




FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/src

COPY job_matcher_app/skill_worker/requirements.skill_worker.txt /app/requirements.skill_worker.txt

RUN pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cpu torch \
    && pip install --no-cache-dir -r /app/requirements.skill_worker.txt

COPY job_matcher_app/skill_worker.py /app/src/job_matcher_app/skill_worker.py

CMD ["python", "-m", "job_matcher_app.skill_worker"]
